// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LC3Text = 1,
  Seperator = 2,
  Comment = 3,
  String = 4,
  Directive = 5,
  OsCall = 6,
  Label = 7,
  OpCode = 8,
  Register = 9,
  Number = 10
